services:
  - type: web
    name: todo-app-backend
    runtime: python3
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: todo-app-db
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: static
    name: todo-app-frontend
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://todo-app-backend-0y08.onrender.com/api
      - key: REACT_APP_GOOGLE_CLIENT_ID
        value: 855568580330-ib4p03q5htkk8h6e3spfri766shnd7p1.apps.googleusercontent.com

databases:
  - name: todo-app-db
    plan: free
